title         : "Chen's blog"
description   : "Blog Abount Programming"
keywords      : "blog, programming, compiler, algorithm"
url           : https://0x7ffc.github.io # site url
baseurl       : ""
cover         : "" # image uri like logo/cover image for site seo

permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

sass:
  sass_dir  : _scss
  style     : compressed # expanded

author:
  name     : "Chen"

social:
  name: Chen
  links:
    - https://github.com/0x7ffc

google_site_verification: LrbQGpNpmw_icgvGLPdKTu5LasO_u7Bu3w2s0xoHrlQ

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - bourbon

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
